### ISSUE TITLE
./gradlew :sirocco-samples:run fails

### ISSUE THREAD

**Issue by MarkusBarthlen** [januslynd/sirocco#6]
./gradlew :sirocco-samples:run

  ./gradlew :sirocco-samples:run

FAILURE: Build failed with an exception.
- Where:
  Build file '/home/markus/git/frege/sirocco/sirocco-core/build.gradle' line: 49
- What went wrong:
  A problem occurred evaluating project ':sirocco-core'.
  
  > Could not find property 'bintrayUser' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@1ddc6db2.
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.api.GradleScriptException: A problem occurred evaluating project ':sirocco-core'.
  at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
  at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(DefaultScriptPluginFactory.java:148)
  at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)
  at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:153)
  at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
  at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
  at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
  at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
  at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:499)
  at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
  at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
  at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
  at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
  at org.gradle.internal.Factories$1.create(Factories.java:22)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
  at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
  at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
  at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
  at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
  at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
  at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
  at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
  at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
  at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
  at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
  at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
  at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
  at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
  at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
  at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
  at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
  at org.gradle.launcher.Main.doAction(Main.java:33)
  at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
  at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
  at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
  at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
  at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
  at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
  at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Caused by: groovy.lang.MissingPropertyException: Could not find property 'bintrayUser' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@416d56f2.
  at org.gradle.api.internal.AbstractDynamicObject.propertyMissingException(AbstractDynamicObject.java:43)
  at org.gradle.api.internal.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:35)
  at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:97)
  at com.jfrog.bintray.gradle.BintrayExtension_Decorated.getProperty(Unknown Source)
  at build_72l46yq5olcg9ovavx2nceatb$_run_closure3.doCall(/home/markus/git/frege/sirocco/sirocco-core/build.gradle:49)
  at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
  at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
  at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
  at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
  at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
  at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
  at build_72l46yq5olcg9ovavx2nceatb.run(/home/markus/git/frege/sirocco/sirocco-core/build.gradle:47)
  at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
  ... 50 more

BUILD FAILED

Total time: 3.924 secs
./gradlew :sirocco-samples:run  7,21s user 0,22s system 172% cpu 4,319 total

---

Also,  the links under

https://github.com/fregelab/sirocco/tree/master/sirocco-docs/src/docs/asciidoc/chapter
## are broken.

Thank you for initating this project. I realize this is a fun project, but hopefully it is fine if I open this issue. I do not have much experience with gradle, so it could be the problem sits in front of the computer.

**Comment by mariogarcia** [comment]
Hi:

First of all sorry to answer you so late. 
- About the first problem, just execute the samples like this

```
./gradlew :sirocco-samples:run -PbintrayUser -PbintrayKey
```

The problem is that for Travis-CI I need to set this in order to execute the whole build, but of course it's not necessary during development. Anyway I will change it in the future in order to avoid that pain to any new developer.
- About the links, don't read the documentation source code, it's mean to be read through the generated html. Just go to https://fregelab.github.io/sirocco/ and read on.

Thanks to take the time to check the project :+1:

**Comment by MarkusBarthlen** [comment]
Awesome, this works (at least with ./gradlew :sirocco-sample:run -PbintrayUser -PbintrayKey
and http://localhost:4567/bands). Thank you very much.

**Comment by mariogarcia** [comment]
You're very welcome @MarkusBarthlen thanks for your feedback :)
